# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-uc-_DHv8yBG_P4oGLzctKEI7Kvb8Jp8
"""

# Kutubxonalarni o'rnatish
import cv2
import matplotlib.pyplot as plt
import numpy as np
from google.colab import files
import os

# Fayllarni yuklash (local yuklash)
uploaded = files.upload()

# Yuklangan rasmlarni oq-qora formatga o'tkazish
for filename in uploaded.keys():
    # Rasmni o'qish
    img = cv2.imread(filename)

    # Oq-qora formatga o'tkazish
    gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # Natijani ko'rsatish
    plt.figure()
    plt.title(f"Oq-qora tasvir: {filename}")
    plt.imshow(gray_img, cmap='gray')
    plt.axis('off')

    # Oq-qora rasmni saqlash
    save_path = f"gray_{filename}"
    cv2.imwrite(save_path, gray_img)
    print(f"Saqlangan fayl: {save_path}")